[package]
name = "hyperscan-sys"
version = "0.2.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "Hyperscan bindings for Rust with Multiple Pattern and Streaming Scan"
homepage = "https://github.com/flier/rust-hyperscan"
repository = "https://github.com/flier/rust-hyperscan"
documentation = "https://docs.rs/crate/hyperscan-sys/"
license = "Apache-2.0"
readme = "README.md"
keywords = ["regex", "hyperscan", "streaming"]
edition = "2018"
links = "hs"

[features]
gen = ["bindgen"]

[dependencies]

[build-dependencies]
log = "0.4"
failure = "0.1"
pretty_env_logger = "0.3"
pkg-config = "0.3"

bindgen = { version = "0.49", optional = true }

[lib]
doctest = false
