dist: bionic

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libhyperscan-dev
      - libpcap-dev
      - llvm-9-dev
      - tree
  homebrew:
    packages:
      - hyperscan
      - libpcap
      - llvm
      - tree

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo build --verbose
  - cargo test --verbose

after_failure:
  - echo `pwd`
  - tree -h
