dist: bionic

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libhyperscan-dev
      - libpcap-dev
      - llvm-9-dev
      - tree
  homebrew:
    packages:
      - hyperscan
      - libpcap
      - pkg-config
      - llvm
      - tree

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - RUST_BACKTRACE=1

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install hyperscan libpcap pkg-config llvm tree && cargo test -v ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd hyperscan && cargo test --no-default-features -v ; fi

after_failure:
  - echo `pwd`
  - tree -h
