[package]
name = "hyperscan"
version = "0.1.1"
authors = ["Flier Lu <flier.lu@nexusguard.com>"]
build = "build.rs"
description = "Hyperscan bindings for Rust"
homepage = "http://flier.github.io/rust-hyperscan/"
repository = "https://github.com/flier/rust-hyperscan"
documentation = "http://flier.github.io/rust-hyperscan/doc/hyperscan/index.html"
license = "Apache-2.0"
readme = "README.md"
keywords = ["regex", "hyperscan", "streaming"]

[dependencies]
libc = "0.2"
log = "0.3"
regex-syntax = "0.3"

[build-dependencies]
bindgen = { git = "https://github.com/Yamakaky/rust-bindgen.git" }
log = "0.3"
env_logger = "0.3"

[dev-dependencies]
env_logger = "0.3"
regex = "0.1"
getopts = "0.2"
pcap = "0.5"
pnet = "0.14"
byteorder = "*"

[lib]
name = "hyperscan"

[[example]]
name = "simplegrep"
path = "examples/simplegrep.rs"
test = false
bench = false

[[example]]
name = "pcapscan"
path = "examples/pcapscan.rs"
test = false
bench = false
