[package]
name = "hyperscan"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@nexusguard.com>"]
build = "build.rs"
description = "Hyperscan bindings for Rust"
homepage = "https://github.com/flier/rust-hyperscan"
repository = "https://github.com/flier/rust-hyperscan.git"
readme = "README.md"
keywords = ["regex", "hyperscan", "streaming"]

[dependencies]
libc = "0.2"
log = "0.3"
regex-syntax = "0.3"

[dev-dependencies]
regex = "0.1"

[lib]
name = "hyperscan"

[[example]]
name = "simplegrep"
path = "examples/simplegrep.rs"
