name: Run tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        toolchain: [stable, nightly]

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq libboost-dev libpcap-dev ragel libhyperscan-dev

    - name: Install ${{ matrix.toolchain }} Rust with clippy and rustfmt
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        components: rustfmt, clippy
        override: true

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-rust-${{ matrix.toolchain }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run cargo test
      run: cargo test --verbose --release

    - name: Run cargo clippy
      run: cargo clippy
