name: Run tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq libboost-dev libpcap-dev ragel libhyperscan-dev

    - name: Install nightly Rust with clippy and rustfmt
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true

    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run cargo test
      run: cargo test --verbose --release

    - name: Run cargo clippy
      run: cargo clippy
