name: Run tests

on: [push, pull_request]

env:
  HYPERSCAN_VERSION: 5.3.0
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Download Hyperscan
      run: |
        wget https://github.com/intel/hyperscan/archive/v$HYPERSCAN_VERSION.tar.gz
        mkdir ${{ github.workspace }}/hyperscan
        tar xvf v$HYPERSCAN_VERSION.tar.gz -C ${{ github.workspace }}/hyperscan --strip-components=1

    - name: Build with CMake
      uses: ashutoshvarma/action-cmake-build@master
      with:
        configure-options: -G Ninja -DBUILD_STATIC_AND_SHARED=on
        build-dir: ${{ runner.workspace }}/build
        build-type: RelWithDebInfo
        source-dir: ${{ github.workspace }}/hyperscan
        install-build: true

    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}


    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
